// ============================================================
// DEVFORGE — Shared Placeholder Data
// Used across all pages for consistent demo content
// ============================================================

export const MEMBERS = [
  { id: '1', name: 'Sarah Kim', role: 'Frontend Lead', avatar: 'SK', online: true },
  { id: '2', name: 'Alex Morgan', role: 'Backend Engineer', avatar: 'AM', online: true },
  { id: '3', name: 'Priya Nair', role: 'DevOps Engineer', avatar: 'PN', online: false },
  { id: '4', name: 'John Doe', role: 'Product Manager', avatar: 'JD', online: true },
  { id: '5', name: 'Lena Zhao', role: 'AI Engineer', avatar: 'LZ', online: false },
  { id: '6', name: 'Carlos Ruiz', role: 'QA Engineer', avatar: 'CR', online: true },
];

export const PROJECTS = [
  {
    id: '1',
    name: 'DevForge UI',
    description: 'Main engineering workspace frontend — React 19 + TypeScript.',
    status: 'active' as const,
    progress: 68,
    language: 'TypeScript',
    color: '#7C3AED',
    issues: 12,
    members: ['SK', 'AM', 'JD'],
    updatedAt: '2 minutes ago',
    sprints: 4,
    starred: true,
  },
  {
    id: '2',
    name: 'API Gateway',
    description: 'High-performance API routing and rate limiting service.',
    status: 'active' as const,
    progress: 82,
    language: 'Go',
    color: '#10B981',
    issues: 4,
    members: ['AM', 'PN'],
    updatedAt: '1 hour ago',
    sprints: 6,
    starred: false,
  },
  {
    id: '3',
    name: 'Auth Service',
    description: 'Zero-trust authentication and authorization platform.',
    status: 'review' as const,
    progress: 45,
    language: 'Rust',
    color: '#F59E0B',
    issues: 8,
    members: ['CR', 'AM', 'SK'],
    updatedAt: '3 hours ago',
    sprints: 2,
    starred: true,
  },
  {
    id: '4',
    name: 'ML Pipeline',
    description: 'Distributed ML model training and serving infrastructure.',
    status: 'backlog' as const,
    progress: 20,
    language: 'Python',
    color: '#3B82F6',
    issues: 21,
    members: ['LZ', 'PN'],
    updatedAt: '1 day ago',
    sprints: 1,
    starred: false,
  },
  {
    id: '5',
    name: 'Notification Service',
    description: 'Real-time push notification and email delivery system.',
    status: 'active' as const,
    progress: 91,
    language: 'Node.js',
    color: '#EF4444',
    issues: 2,
    members: ['AM', 'CR'],
    updatedAt: '30 minutes ago',
    sprints: 3,
    starred: false,
  },
  {
    id: '6',
    name: 'Analytics Engine',
    description: 'Real-time data aggregation and business intelligence.',
    status: 'paused' as const,
    progress: 35,
    language: 'Kotlin',
    color: '#8B5CF6',
    issues: 15,
    members: ['JD', 'LZ'],
    updatedAt: '2 days ago',
    sprints: 1,
    starred: false,
  },
];

export const TASKS = [
  {
    id: 't1',
    title: 'Implement OAuth2 PKCE flow',
    priority: 'high' as const,
    assignee: 'AM',
    label: 'Auth',
    status: 'todo' as const,
    points: 5,
  },
  {
    id: 't2',
    title: 'Design token migration to CSS vars',
    priority: 'medium' as const,
    assignee: 'SK',
    label: 'Frontend',
    status: 'todo' as const,
    points: 3,
  },
  {
    id: 't3',
    title: 'Write API rate limit specs',
    priority: 'low' as const,
    assignee: 'JD',
    label: 'Docs',
    status: 'todo' as const,
    points: 2,
  },
  {
    id: 't4',
    title: 'Refactor database connection pool',
    priority: 'high' as const,
    assignee: 'AM',
    label: 'Backend',
    status: 'inprogress' as const,
    points: 8,
  },
  {
    id: 't5',
    title: 'Build sidebar collapse animation',
    priority: 'medium' as const,
    assignee: 'SK',
    label: 'Frontend',
    status: 'inprogress' as const,
    points: 3,
  },
  {
    id: 't6',
    title: 'Set up Kubernetes HPA',
    priority: 'high' as const,
    assignee: 'PN',
    label: 'Infra',
    status: 'inprogress' as const,
    points: 5,
  },
  {
    id: 't7',
    title: 'Code review: auth middleware',
    priority: 'medium' as const,
    assignee: 'CR',
    label: 'Review',
    status: 'review' as const,
    points: 2,
  },
  {
    id: 't8',
    title: 'E2E tests for login flow',
    priority: 'high' as const,
    assignee: 'CR',
    label: 'QA',
    status: 'review' as const,
    points: 5,
  },
  {
    id: 't9',
    title: 'Deploy auth service v2.1',
    priority: 'low' as const,
    assignee: 'PN',
    label: 'Infra',
    status: 'done' as const,
    points: 1,
  },
  {
    id: 't10',
    title: 'Update changelog for v1.8',
    priority: 'low' as const,
    assignee: 'JD',
    label: 'Docs',
    status: 'done' as const,
    points: 1,
  },
];

export const PRIORITY_CONFIG = {
  critical: {
    label: 'Critical',
    color: 'text-[var(--df-danger)] bg-[var(--df-danger)]/10 border-[var(--df-danger)]/20',
  },
  high: {
    label: 'High',
    color: 'text-[var(--df-danger)] bg-[var(--df-danger)]/10 border-[var(--df-danger)]/20',
  },
  medium: {
    label: 'Medium',
    color: 'text-[var(--df-warning)] bg-[var(--df-warning)]/10 border-[var(--df-warning)]/20',
  },
  low: {
    label: 'Low',
    color: 'text-[var(--df-success)] bg-[var(--df-success)]/10 border-[var(--df-success)]/20',
  },
};

export const STATUS_CONFIG = {
  active: {
    label: 'Active',
    dot: 'bg-[var(--df-success)]',
    badge: 'text-[var(--df-success)] bg-[var(--df-success)]/10',
  },
  review: {
    label: 'In Review',
    dot: 'bg-[var(--df-warning)]',
    badge: 'text-[var(--df-warning)] bg-[var(--df-warning)]/10',
  },
  backlog: {
    label: 'Backlog',
    dot: 'bg-[var(--df-muted-fg)]',
    badge: 'text-[var(--df-muted-fg)] bg-[var(--df-secondary)]',
  },
  paused: {
    label: 'Paused',
    dot: 'bg-[var(--df-danger)]',
    badge: 'text-[var(--df-danger)] bg-[var(--df-danger)]/10',
  },
};

export const ACTIVITY_FEED = [
  {
    type: 'commit',
    user: 'Sarah K.',
    avatar: 'SK',
    msg: 'feat: implement real-time collaboration layer',
    repo: 'devforge-ui',
    time: '4m ago',
    branch: 'feat/collab',
  },
  {
    type: 'deploy',
    user: 'Pipeline',
    avatar: 'CI',
    msg: 'Deployment to production succeeded',
    repo: 'api-gateway',
    time: '12m ago',
    branch: 'main',
  },
  {
    type: 'review',
    user: 'Alex M.',
    avatar: 'AM',
    msg: 'Approved PR: database connection pool refactor',
    repo: 'backend',
    time: '28m ago',
    branch: 'fix/pool',
  },
  {
    type: 'issue',
    user: 'Priya N.',
    avatar: 'PN',
    msg: 'Opened issue: K8s HPA config missing limits',
    repo: 'infra',
    time: '45m ago',
    branch: null,
  },
  {
    type: 'comment',
    user: 'Carlos R.',
    avatar: 'CR',
    msg: 'Left 3 comments on auth middleware review',
    repo: 'auth-service',
    time: '1h ago',
    branch: 'feat/auth',
  },
  {
    type: 'merge',
    user: 'Lena Z.',
    avatar: 'LZ',
    msg: 'Merged: ML model serving endpoint v2',
    repo: 'ml-pipeline',
    time: '2h ago',
    branch: 'feat/serve',
  },
];

export const NOTIFICATIONS_DATA = [
  {
    id: '1',
    type: 'success',
    title: 'Deployment successful',
    body: 'devforge-ui@v1.2.4 deployed to production',
    time: '2m ago',
    read: false,
    category: 'Deployments',
  },
  {
    id: '2',
    type: 'warning',
    title: 'Sprint deadline approaching',
    body: 'Sprint #12 ends in 2 days — 4 tasks remaining',
    time: '1h ago',
    read: false,
    category: 'Sprints',
  },
  {
    id: '3',
    type: 'info',
    title: 'New team member',
    body: 'Sarah Kim joined the Engineering workspace',
    time: '3h ago',
    read: true,
    category: 'Team',
  },
  {
    id: '4',
    type: 'error',
    title: 'Build failed',
    body: 'CI pipeline on feat/ai-suggestions failed at test stage',
    time: '5h ago',
    read: true,
    category: 'CI/CD',
  },
  {
    id: '5',
    type: 'info',
    title: 'PR review requested',
    body: 'Alex Morgan requested your review on database-pool PR',
    time: '6h ago',
    read: true,
    category: 'Code Review',
  },
  {
    id: '6',
    type: 'success',
    title: 'API key created',
    body: 'New API key "Production v2" was created successfully',
    time: '1d ago',
    read: true,
    category: 'Security',
  },
];
